version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Docker - docker/openemr/7.0.3
  - package-ecosystem: "docker"
    directory: "/docker/openemr/7.0.3"
    schedule:
      interval: "daily"

  # Docker - docker/openemr/7.0.4
  - package-ecosystem: "docker"
    directory: "/docker/openemr/7.0.4"
    schedule:
      interval: "daily"

  # Docker - docker/openemr/7.0.5
  - package-ecosystem: "docker"
    directory: "/docker/openemr/7.0.5"
    schedule:
      interval: "daily"

  # Docker - docker/openemr/flex
  - package-ecosystem: "docker"
    directory: "/docker/openemr/flex"
    schedule:
      interval: "daily"

  # Docker Compose - docker/openemr
  - package-ecosystem: "docker"
    directory: "/docker/openemr"
    schedule:
      interval: "daily"

  # Docker Compose - packages/appliance
  - package-ecosystem: "docker"
    directory: "/packages/appliance"
    schedule:
      interval: "daily"

  # Docker Compose - utilities/mariadb-backup-manager
  - package-ecosystem: "docker"
    directory: "/utilities/mariadb-backup-manager"
    schedule:
      interval: "daily"

  # Docker Compose - utilities/openemr-monitor
  - package-ecosystem: "docker"
    directory: "/utilities/openemr-monitor"
    schedule:
      interval: "daily"
